### PR TITLE
Add ability to specify a custom transformation to apply to the current Bitmap

### PR DESCRIPTION
**Pull request by mbrubin56**
* Add a new interface, Transform, that clients can implement to apply a custom transformation to the GIF's current Bitmap.
* Reimplemented the rounded corners implementation as an implementation of Transform.

### CODE REVIEW

**Comment by koral--** [comment]
Thanks, apart from comments above LGTM.

**Comment by mbrubin56** [comment]
Thanks for the comments! I agree with them (sorry I mistranslated that corner radius from a float to an int). Everything should be addressed with ac83411090d80270cdf412cb0cf5743a682baafa.

**Comment by mbrubin56** [comment]
Oh, and I should also take the time to thank you for the lovely library.

**Comment by koral--** [comment]
Merged into dev branch with minor tweaks. This PR will be closed automatically when commit gets merged into the master.

**Pull request merged**
